# **NumPy**

* NumPy is a Python library used for working with `array`.

* It also has function for working in domain of linear algebra, fourier transform, and matrices.

* NumPy was created in `**2005**` by `Travis Oliphant`. It is an open-source project and you can use it freely.

* NumPy stands for `Numerical Python`.

In [1]:
import numpy as np

In [2]:
arr = np.array([10, 20, 30, 40, 50])
print(arr)

[10 20 30 40 50]


In [3]:
# check numpy version
print(np.__version__)

2.3.4


# **`NumPy Creating Arrays`**

In [4]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)

# to get type of the 'arr' variable 
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


**`Dimensions in Array`**

**`0-D array`**

In [5]:
arr = np.array(32)
print(arr)

32


**`1-D array`**

In [6]:
arr = np.array([2, 4, 6, 8])
print(arr)

[2 4 6 8]


**`2-D array`**

In [7]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


**`3-D array`**

In [8]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


**`Check Number of Dimensions?`**: here i am using `ndim`attribute.

In [9]:
arr1 = np.array(42)
arr2 = np.array([10, 20, 30, 40, 50])
arr3 = np.array([[1, 2, 3], [4, 5, 6]])
arr4 = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr1.ndim) 
print(arr2.ndim)
print(arr3.ndim)
print(arr4.ndim) # number of dimensions


0
1
2
3


# **`Access Array Elements`**

In [10]:
# access 1-D array:- 
arr = np.array([10, 20, 30, 40, 50])
print(arr[2])
print(arr[2] + arr[4])

30
80


In [11]:
# access 2-D array:-
arr = np.array([[1, 2, 3], [4, 5, 6]])

print(arr[1, 2])
print(arr[0, 1])

6
2


In [12]:
# access 3-D array:-
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

print(arr[1, 0, 1])
print(arr[0, 1, 0])

6
3


# **`Slicing`**

In [13]:
# # SLICING WITH 1-D ARRAY:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# slicing:
print(arr[1:4])
print(arr[4:])
print(arr[:8])

# slicing with steps:
print(arr[1:8:2])
print(arr[::2])

[20 30 40]
[ 50  60  70  80  90 100]
[10 20 30 40 50 60 70 80]
[20 40 60 80]
[10 30 50 70 90]


In [14]:
# SLICING WITH 2-D ARRAY:
arr = np.array([[1, 2, 3, 7, 8], [4, 5, 6, 9, 10], [5, 7, 90, 2, 9]])
print(arr[1, 1:4])
print(arr[0:3, 2])

print(arr[0:3, 1:4])

[5 6 9]
[ 3  6 90]
[[ 2  3  7]
 [ 5  6  9]
 [ 7 90  2]]


In [15]:
# Slicing with 3-D array: 
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
print(arr[2, 1, 0:2])

[11 12]


# **`Data Types`**

In [16]:
# by default python have these data types:
'''
   string
   integer
   float
   boolean
   complex
'''

'\n   string\n   integer\n   float\n   boolean\n   complex\n'

In [17]:
# library data types:
'''
i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )
'''

'\ni - integer\nb - boolean\nu - unsigned integer\nf - float\nc - complex float\nm - timedelta\nM - datetime\nO - object\nS - string\nU - unicode string\nV - fixed chunk of memory for other type ( void )\n'

**`checking the data type of an array`**

In [18]:
arr = np.array([1, 2, 3, 4, 5])
print(arr.dtype)

int64


In [19]:
arr = np.array(['ayushi', 'mohan', 'sohan', 'anuj'])
print(arr.dtype)

<U6


# **`Array Copy vs View`**

In [20]:
arr = np.array([1, 2, 3, 4, 5])

copy_arr = arr.copy()
arr[0] = 35
copy_arr[1] = 67

print("Original array: ", arr)
print("Copy of the array: ", copy_arr)

Original array:  [35  2  3  4  5]
Copy of the array:  [ 1 67  3  4  5]


In [21]:
arr = np.array([1, 2, 3, 4, 5])

copy_arr = arr.view()
arr[0] = 35
copy_arr[1] = 67

print("Original array: ", arr)
print("View of the array: ", copy_arr)

Original array:  [35 67  3  4  5]
View of the array:  [35 67  3  4  5]


In [22]:
arr = np.array([1, 2, 3, 4, 5])

c = arr.copy()
v = arr.view()

print(c.base) # the copy returns "None"
print(v.base) # the view returns the original array

None
[1 2 3 4 5]


# **`Shape of an array`**

In [23]:
arr = np.array([[1, 2, 3, 7, 8], [4, 5, 6, 9, 10], [5, 7, 90, 2, 9]])
print(arr.shape)

(3, 5)


# **`Re-shaping`**

`1-D to 2-D`

In [24]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_arr = arr.reshape(3, 4)
print(new_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


`1-D to 3-D`

In [25]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

new_arr = arr.reshape(3, 2, 2)                            
print(new_arr)

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


# **`Iteration`**

In [26]:
arr = np.array([1, 2, 3, 4, 5])

for x in arr:
    print(x)

1
2
3
4
5


In [27]:
arr = np.array([[1, 2, 3, 7, 8], [4, 5, 6, 9, 10], [5, 7, 90, 2, 9]])
for x in arr:
    for y in x:
            print(y)

1
2
3
7
8
4
5
6
9
10
5
7
90
2
9


In [28]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for a in arr:
    for b in a:
        for c in b:
            print(c)

1
2
3
4
5
6
7
8


In [29]:
arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

for e in np.nditer(arr):
    print(e)

1
2
3
4
5
6
7
8


# **`Joining`**

In [30]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [31]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [32]:
# stack() function:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.stack((arr1, arr2), axis=1)
print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [33]:
# hstack() function:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))
print(arr)

[1 2 3 4 5 6]


In [34]:
# vstack() function:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))
print(arr)

[[1 2 3]
 [4 5 6]]


# **`Spliting`**

**Splitting is reverse operation of joining. Joining merges multiple arrays into one and spliting break one array into multiple.**

**`split 1-D array`**

In [35]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = np.array_split(arr, 3)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [36]:
arr = np.array([1, 2, 3, 4, 5, 6])
new_arr = np.array_split(arr, 4)
print(new_arr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [37]:
print(new_arr[0])
print(new_arr[1])
print(new_arr[2])
print(new_arr[3])

[1 2]
[3 4]
[5]
[6]


**`split 2-D array`**

In [38]:
arr = np.array([[1,2], [3,4], [5,6], [7,8], [9,10], [11,12]])
new_arr = np.array_split(arr, 3)
print(new_arr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [39]:
for i in new_arr:
    print(i)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


# `Searching Arrays`:here i am using `where()` method.

In [40]:
arr = np.array([1, 2, 3, 4, 5, 6])

s_arr = np.where(arr == 5)
print(s_arr)

(array([4]),)


In [41]:
arr = np.array([1, 2, 3, 4, 5, 6])

s_arr = np.where(arr%2 == 0)
print(s_arr) 

(array([1, 3, 5]),)


In [42]:
arr = np.array([1, 2, 3, 4, 5, 6])

s_arr = np.where(arr%2 == 1)
print(s_arr)

(array([0, 2, 4]),)


using `searchsorted()` method

In [43]:
arr = np.array([1, 2, 3, 4, 5, 6])

s_arr = np.searchsorted(arr, 5)
print(s_arr)

4


In [44]:
arr = np.array([1, 2, 3, 4, 5, 6])

s_arr = np.searchsorted(arr, 4, side="right")
print(s_arr) # when we use "right" or "left" it tells the position of the value

4


In [45]:
arr = np.array([1, 2, 3, 4, 5, 6])

s_arr = np.searchsorted(arr, [1, 4, 6])
print(s_arr)

[0 3 5]


# **`Sorting`**

In [46]:
arr = np.array([5, 8, 2, 4, 0, 5, 9])
print(np.sort(arr))

[0 2 4 5 5 8 9]


In [47]:
arr = np.array(['sohan', 'mohan', 'ayushi', 'anuj', 'tushar', 'rahul', 'radhika'])
print(np.sort(arr))

['anuj' 'ayushi' 'mohan' 'radhika' 'rahul' 'sohan' 'tushar']


In [48]:
arr = np.array(['sohan', 'mohan', 8, 'Anuj', 5, 'Rahul'])
print(np.sort(arr))

['5' '8' 'Anuj' 'Rahul' 'mohan' 'sohan']


# **`Filtering`**


* Getting some elements out of an array based on creating a new array out of them is called filtering.

* in NumPy, you filter an array using a 'boolrean index' list.

* A boolean index list is a list of boolean corresponding to indexes in the array.


In [49]:
arr = np.array([45, 23, 22, 56, 78, 44])
index = [True, False, False, True, True, True]

new_arr = arr[index]
print(new_arr)

[45 56 78 44]


In [50]:
arr = np.array([45, 23, 22, 56, 78, 44])

index = []

for e in arr:
    if e > 42:
        index.append(True)
    else:
        index.append(False)
        
new_arr = arr[index]
print(new_arr)

[45 56 78 44]


In [51]:
arr = np.array([45, 23, 22, 56, 78, 44])

index = []

for e in arr:
    if e > 42:
        index.append(True)
    else:
        index.append(False)
        
new_arr = arr[index]

print(index)
print(new_arr)

[True, False, False, True, True, True]
[45 56 78 44]


In [52]:
arr = np.array([45, 23, 22, 56, 78, 44])

index = []

for e in arr:
    if e%2 == 0:
        index.append(True)
    else:
        index.append(False)
        
new_arr = arr[index]
print(new_arr)

[22 56 78 44]


In [53]:
arr = np.array([45, 23, 22, 56, 78, 44])

index = arr > 43
new_arr = arr[index]

print(index)
print(new_arr)

[ True False False  True  True  True]
[45 56 78 44]


In [54]:
arr = np.array([45, 23, 22, 56, 78, 44])

index = arr%2 == 0
new_arr = arr[index]
        
print(index)
print(new_arr)

[False False  True  True  True  True]
[22 56 78 44]


# **`Random`**

In [55]:
from numpy import random

In [56]:
rnd = random.randint(100)
print(rnd)

38


In [57]:
rnd = random.rand()
print(rnd)

0.2747531826349917


**`create an array by random number:`**

In [58]:
rnd = random.randint(50, size=(5))
print(rnd)

[13 46  6  7 27]


In [59]:
rnd = random.randint(50, size=(3, 4))
print(rnd)

[[13 21 41  4]
 [20 41 45 27]
 [16 19 29 15]]


In [60]:
rnd = random.rand(5)
print(rnd)

[0.11262819 0.52137659 0.64827096 0.60287001 0.35055867]


In [61]:
rnd = random.rand(3, 4)
print(rnd)

[[0.0875453  0.16671649 0.14848294 0.04190426]
 [0.08959148 0.93869384 0.1770606  0.79499868]
 [0.48391269 0.67595322 0.20307224 0.61418746]]


**`generate random number from array`**

In [62]:
rnd_val = random.choice([4, 7, 2, 9, 6, 1])
print(rnd_val)

2


In [63]:
rnd_val = random.choice([4, 7, 2, 9, 6, 1], size=(3, 5))
print(rnd_val)

[[9 7 1 1 9]
 [9 1 4 2 7]
 [9 1 4 2 2]]


# **`Random Permutations`**

`shuffle() and permutation()`

In [64]:
arr = np.array([1, 2, 3, 4, 5])
random.shuffle(arr)
print(arr)

# `shuffle()` method makes changes to the original array.

[4 2 5 3 1]


In [65]:
arr = np.array([1, 2, 3, 4, 5])
new_arr = random.permutation(arr)
print("new_arr: ", new_arr)
print("original arr: ", arr)

# `permutation()` method returns a re-arranged array (and leaves the original array unchanged).

new_arr:  [2 3 1 5 4]
original arr:  [1 2 3 4 5]
